services:
  - type: web
    name: weather-image-classification-api
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    disk:
      name: results-storage
      mountPath: /opt/render/project/src/results
      sizeGB: 1
